# Generated by Django 3.1.7 on 2021-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('all_day', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('desc', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=100)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
