# Generated by Django 3.1.7 on 2021-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210308_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(default='asdf', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(default='asdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='asdf', max_length=30),
        ),
    ]
