# Generated by Django 3.1.7 on 2021-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210318_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
