# Generated by Django 3.1.7 on 2021-03-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210318_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
